### ISSUE TITLE
how to run this server

### ISSUE THREAD

**Issue by jamieb452** [MisterCalvin/swat4-server-docker#2]
Hello there,

how would i go about installing and runnning? thanks

**Comment by MisterCalvin** [comment]
You will need to install Docker, here are some instructions from the [official source](https://docs.docker.com/engine/install/). After Docker is installed, clone this repository, cd into the newly created repo folder, and use a text editor to modify `docker-compose.yml`. Set the correct path to your [gamefiles](https://github.com/MisterCalvin/swat4-server-docker/blob/8b373a39a242d38d4aaca365fc34c3ff62e52c04/docker-compose.yml#L24) in the volumes section, save and quit your text editor, then do a `docker compose up -d` from within the same directory. If everything goes well your server will be online within a minute or two. You can watch the logs with `docker logs -f swat4-server-docker`, or run `docker ps` to see the current status of your container.
